<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Infrastructure\Common.Infrastructure.csproj" />
    <ProjectReference Include="..\Domain\Modules.Orders.Domain.csproj" />
    <ProjectReference Include="..\Application\Modules.Orders.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="Dapper" Version="2.1.28" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Modules.Orders.Presentation" />
    <InternalsVisibleTo Include="API.Gateway" />
  </ItemGroup>

</Project>
